server:
  contextPath: /api
  port: 8080

multipart:
  max-file-size: 2Mb
  max-request-size: 2Mb

storage:
  location: /Users/matan/Downloads/gift/files

outbound:
  smsDisabled: true

#logging.level.org.springframework.web: DEBUG
