server:
  contextPath: /api
  port: 8080

multipart:
  max-file-size: 2Mb
  max-request-size: 2Mb

storage:
  location: /files

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: giftDB
      username: gift-service-core
      password: gift-service-core1234

outbound:
  smsDisabled: true

#logging.level.org.springframework.web: DEBUG
