server:
  contextPath: /api/v1
  port: 443
  ssl:
    key-store: classpath:keystore.p12
    key-password: giftapp
    key-store-password: giftapp
    key-store-type: PKCS12
    key-alias: gift
#    ciphers: ECDHE_RSA_WITH_AES_256_CBC_SHA384,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA256,TLS_RSA_WITH_AES_256_CBC_SHA
    protocol: TLS

multipart:
  max-file-size: 2Mb
  max-request-size: 2Mb

storage:
  location: files

spring:
  datasource:
      url: jdbc:mysql://gifted-dev.crat39jstzvs.eu-central-1.rds.amazonaws.com:3306/giftdb
      username: root
      password: admin123
      driver-class-name: com.mysql.cj.jdbc.Driver
      # Keep the connection alive if idle for a long time (needed in production)
      testWhileIdle: true
      validationQuery: SELECT 1
  jpa:
#    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

security:
  identityPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAkjy7X0THjUNp2rEdAI5WYIiKoUATPdcXmyBRPjcxCSW/tETeb8BSEeHU8ahRygFkKFJxt1bNpR/UZnbE50QmD1xx8V6SaDj5mTZeODJx8+QcaTii+BGDuKqvb44hLAG5FhQa5cOy6XuOkvtKudan2NMeY97pfZahSNXLJrJTrfvPLpXste6BV/B5+j2DhU2fJeAsHfqUEPreNPOxz38Da9WpQ/GmJzEawRPQE1GBh0BE3pLqQOWjf3UL8a76y37eTEVy81R90LxO7zTWdMWPgtmvX6UULXDp3jH9HIikX91upGrqYkatHHBV4Ck7KlAK2WJ/nvG2nGyMR/M5ZaC+LwIDAQAB
  identityPrivateKey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCSPLtfRMeNQ2nasR0AjlZgiIqhQBM91xebIFE+NzEJJb+0RN5vwFIR4dTxqFHKAWQoUnG3Vs2lH9RmdsTnRCYPXHHxXpJoOPmZNl44MnHz5BxpOKL4EYO4qq9vjiEsAbkWFBrlw7Lpe46S+0q51qfY0x5j3ul9lqFI1csmslOt+88uley17oFX8Hn6PYOFTZ8l4Cwd+pQQ+t4087HPfwNr1alD8aYnMRrBE9ATUYGHQETekupA5aN/dQvxrvrLft5MRXLzVH3QvE7vNNZ0xY+C2a9fpRQtcOneMf0ciKRf3W6kaupiRq0ccFXgKTsqUArZYn+e8bacbIxH8zlloL4vAgMBAAECggEAQILYKcPewDugA+CkKa2g/z7c4RuyIVK00DMmg+q3EBD+C9lhwyy1R7w3Q0/8nL+WXo9YKQf6+kAbZAQ7Asa2f4pJnbAZqC6SNXudfu8KBAx6WBSrGAIp+JobgHvTuGUeMFY4M2nskEF4ePCwW2ENdIJV4rrgiA2eItJlpzF95r8HRa/h6hNP5+5Zdt7KmJQkJwvnr3s8ki2uUljya43WhMHbPyb7y6nI3epjYHTfZI2opQ8Br6Fa2r4+2FXEnGdOshZTKcEM8a8rON9XzCcloaSoCY2IJLeEA3wufVCJTBWNExwoNHAcibuBR00fcjWX57SVcZt6MN2ocGXtpe+jYQKBgQDBnPFUPVNlElWMFgwj91aytQPAKrfm2/dAXj+8DshLAZDVu8dPulXqhoR/iZSPIIRA4/2Dkiv/T09WGS8R8iu6dpvCY1aZaZx6FKtzDZLTjvKLR2MdRPGykH7mDGwjmMR59BThYb4mfx4bm7CFTpwhDeRRchLqjUmdISQcKk5bsQKBgQDBW8cvkbLC/LgqB+2sqtnh4mMtAdYJfNwDfbgWngJ44sLY45Ivy4azTvV8src4HG8Fii8xXwgtxcGnud/cOHPCkgeuRvk4NOYtzufGLHBACD+jaBrYynt5DNPuwG1XcnKC70hTQLo+21//JVx3R1dGE5oLhBus5WxLDf6nrVeP3wKBgQCMFPpCodBJy3cb0QPdreILkI5zJjVCkhoVd1uTu/pM0ogxLBir5byt37/T6v4ShEtMC+jrngG5Sm+zcqssx9O9qH1PqsIIY3I0neniZ4q5CK8R+IeMsMpTENrPpWNEag6V0fSdkTOb9NMa1I1mFhc+jyeHigqHq8v8JPNUcYOaMQKBgQCRT8vtr+1MJGizDapMrUl5PI2T8WFNWAxwgzapqK3q81/DZ6MhUC826gwLXrPa82NsImE9FVIsNAZJaqMV+Ubl3qDvFF+PIhIqMuh0QklJleldgItMiT8pxb4wG2UQ5u2wAOu1xVsyieMm+Ij5CyBHhcurA+lYkkJEVYwfr2GyuQKBgGAJ0ayoUG821MJw7sSiY3EToeHoNzmo0w8AbuCCzURQc7McICNmuYNJPNAdRD7dcHIj91w6Nu6CabLQk9r3HeN6Cr8Y08QpoxyC2dL7kxHn2FkW9r3z1Cm1O15gspOPOcfLPrvzcO49HfkOtIc/ldpQCDq9Q5qoPmOdVREm5k7N
  token:
    header: Authorization
    expiration: 604800
  require-ssl: true

outbound:
  smsDisabled: true

#logging.level.org.springframework.web: DEBUG
